#dataset: "NYU" # "kitti", "kitti_360"
dataset: kitti_360

n_relations: 4

enable_log: true
kitti_root: '/data4/sas20048/SSCBench/KITTI360'
kitti_preprocess_root: '/data4/sas20048/SSCBench/KITTI360/preprocess'
kitti_logdir: '/data4/sas20048/SSCBench/results/kitti'

kitti_360_root: '/data4/sas20048/SSCBench/KITTI360'
kitti_360_preprocess_root: '/data4/sas20048/SSCBench/KITTI360/preprocess'
kitti_360_logdir: '/data4/sas20048/SSCBench/results/kitti360'

nuscenes_root: '/data4/sas20048/SSCBench/nuScenes'
nuscenes_preprocess_root: '/data4/sas20048/SSCBench/nuScenes/preprocess_uni'
nuscenes_logdir: '/data4/sas20048/SSCBench/results/nuscenes'

waymo_root: '/data4/sas20048/SSCBench/waymo'
waymo_preprocess_root: '/data4/sas20048/SSCBench/waymo/preprocess'
waymo_logdir: '/data4/sas20048/SSCBench/results/waymo'

NYU_root: '/path/to/NYU/depthbin'
NYU_preprocess_root: '/path/to/NYU/preprocess/folder'
logdir: '/path/to/NYU/logdir'

output_path:  '/data4/sas20048/SSCBench/results/monoscene'

fp_loss: true 
frustum_size: 8 
batch_size: 8
n_gpus: 4
num_workers_per_gpu: 1
exp_prefix: "exp"
run: 1
lr: 1e-4
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: false
project_1_4: false
project_1_8: false
